# Generated by Django 5.1.4 on 2024-12-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofencing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinout',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkinout',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
